window.CITY_MANAGER_PEPPERVILLE = {
  meta: {
    title: `City Manager: Pepperville`,
    subtitle: `Master data file for the Pepperville rebuild`,
    lastUpdated: `2026-05-30`,
  },
  lore: [
    `Pepperville is the main city in Chattawa County.`,
    `Chattawa Valley is the broader region around Chattawa County and the river.`,
    `Ringwald and Lake Ringwald are part of the world canon.`,
    `St. Hilton is the exclusive wealthy district in Chattawa County.`,
    `Wakona Nation is the cultural/tourist area in Chattawa County.`,
    `Noel is the mountain Christmas tourist town in Chattawa County.`,
    `Wonderland characters can use a shared Wonderland tag and tend to cluster together in cities.`,
    `Historic characters can arrive by time travel.`,
    `Source materials have been standardized for the Pepperville rebuild.`,
  ],
  people:[
    {
      name: `Abe Lincoln`,
      value: 10,
      occupation: `President`,
      preferences: `Government; Patriotic; Church; Education; Law Enforcement`,
      tags: [`Government`, `Patriotic`, `Historic`, `Pepperville Historic District`],
      notes: `This is a historic character, and they can arrive by time travel.`,
    },
    {
      name: `Ahmed Ali`,
      value: 2,
      occupation: `Physician, Chattawa Valley Urgent Care; Musician`,
      preferences: `Transportation; Government; Retail; Medical; Egypt`,
      tags: [`Medical`, `Egypt`, `Pepper Hill`],
      notes: `This is a shared character across multiple games.`,
    },
    {
      name: `Alice in Wonderland`,
      value: 3,
      occupation: `Explorer`,
      preferences: `Fairytale Lake & Forest; Library; Cultural Arts Center; Alice in Wonderland; -1 for Queen of Hearts`,
      tags: [`Hats`, `Story`],
      notes: `This is a Wonderland character.`,
    },
    {
      name: `Amelia Earhart`,
      value: 8,
      occupation: `Local Celebrity; Pilot`,
      preferences: `Law Enforcement; Government; Automotive; Media; Museum`,
      tags: [`Historic`, `Pepperville Historic District`],
      notes: `This is a shared character.`,
    },
    {
      name: `Angel Sweet`,
      value: 3,
      occupation: `Guest Services at the Zoo; Budding Christian Musician`,
      preferences: `Church; Animals; Music`,
      tags: [`Pepperville`, `Real Estate`],
      notes: `This is a shared character across Pepperville and the Zoo/Game worlds.`,
    },
    {
      name: `Benjamin Franklin`,
      value: 8,
      occupation: `Founding Father`,
      preferences: `Government; Transportation; Patriotic; Media`,
      tags: [`Patriotic`, `Historic`, `Pepperville Historic District`],
      notes: `This is a historic character, and they can arrive by time travel.`,
    },
    {
      name: `Bess Whizzlekins`,
      value: 2,
      occupation: `English/Language Arts Teacher at Chattawa Valley High School; Singer`,
      preferences: `Children; Education; Music`,
      tags: [`Pepperville`, `Financial`],
    },
    {
      name: `Big Bad Wolf`,
      value: -3,
      occupation: `Currently Unemployed`,
      preferences: `Little Red Riding Hood; Alice in Wonderland; Fairytale Lake & Forest; Park System; Story Unicorn Habitat`,
      tags: [`Animal`, `Story`],
      notes: `This is a negative Animal People card.`,
    },
    {
      name: `Billy the Kid`,
      value: -7,
      occupation: `Outlaw`,
      preferences: `Criminals; Attorneys; Casinos; Bank; Jewelry`,
      tags: [`Criminals`, `Hats`, `Pepperville Historic District`],
      notes: `This is a historic character, and they can arrive by time travel.`,
    },
    {
      name: `Blackbeard the Pirate`,
      value: -8,
      occupation: `Pirate`,
      preferences: `Sailors; Casinos; Museum; Bank; Jewelry`,
      tags: [`Sailors`, `Historic`, `Pepperville Historic District`],
      notes: `This is a historic character, and they can arrive by time travel.`,
    },
    {
      name: `Buzz Smiley`,
      value: 3,
      occupation: `Owner - Pepperville AutoMall`,
      preferences: `Automotive; Local Celebrities; Government; Sports; Transportation`,
      tags: [`Pepperville`, `Medical`],
      notes: `This is a shared character who appears in The Empty Suit, and he owns Pepperville AutoMall and Smiley Rent-A-Car.`,
    },
    {
      name: `Captain Dependable`,
      value: 5,
      occupation: `Superhero`,
      preferences: `Amusement Park; Local Celebrities; Media; Retail; Casinos`,
      cardType: `special`,
      tags: [`Pepperville`, `Arts`, `Events`],
      notes: `This is a special card. All City Managers bid on it. When you win it, add 5 population to your city and discard all negative People cards in your city.`,
    },
    {
      name: `Captain Zoogle`,
      value: 4,
      occupation: `Children’s TV Show Host`,
      preferences: `Animals; Sailors; Education`,
      tags: [`Sailors`, `Animal`, `Pepperville`],
      notes: `This card counts as Animal because of the parrot in the photo, and the character lives in Pepperville.`,
    },
    {
      name: `Chen Wu, MD`,
      value: 2,
      occupation: `Physician - Pepperville Eye Clinic`,
      preferences: `Medical; Accountants; Insurance; Attorneys; Bank`,
      tags: [`Medical`, `Pepperville`],
      notes: `This character is the father of Ming Wu.`,
    },
    {
      name: `Duke Callahan`,
      value: 6,
      occupation: `Local Celebrity; Former Professional Baseball Player`,
      preferences: `Sports; Transportation; Law Enforcement; Government; Riverwalk`,
      tags: [`Pepperville Riverwalk`, `Retail`],
      notes: `This is a shared character, and he owns Callahan Hardware in Pepperville lore.`,
    },
    {
      name: `Dr. Antonio Tiramisu`,
      value: 8,
      occupation: `Superintendent, Chattawa County School System`,
      preferences: `Education; Media`,
      tags: [`Pepperville`, `Automotive`],
      notes: `This character is the brother of Romeo and Giuseppe Tiramisu.`,
    },
    {
      name: `Fire Chief Hank Hatley`,
      value: 8,
      occupation: `Chattawa County Fire Chief`,
      preferences: `Government; Law Enforcement`,
      tags: [`Pepperville`, `Retail`, `Restaurant`],
      notes: `This character protects restaurants from the Radical Animal Rights Demonstration.`,
    },
    {
      name: `Judith Pepper`,
      value: 2,
      occupation: `Nurse`,
      preferences: `Medical`,
      tags: [`Pepperville`, `Retail`],
      notes: `This character is Jimmy Pepper's wife.`,
    },
    {
      name: `Josh Patel`,
      value: 2,
      occupation: `Pharmacist`,
      preferences: `Medical; Insurance; Education; Restaurant`,
      tags: [`Pepperville`, `Pest Control`],
    },
    {
      name: `Marcus Johnson`,
      value: 5,
      occupation: `Evening News Anchor - WPEP Channel 7`,
      preferences: `Media; Events; Local Celebrities; Government; Tourist Attraction`,
      tags: [`Media`, `Events`, `Local Celebrities`, `Pepperville`],
    },
    {
      name: `Mayor Joyce Romano Pepper`,
      value: 8,
      occupation: `Mayor of Pepperville`,
      preferences: `Pepperville`,
      tags: [`Government`, `Pepperville`],
      notes: `This character is married to Winfred Pepper and is the mother of Johnny and Jimmy Pepper. Her maiden and middle name is Romano.`,
    },
    {
      name: `Cheshire Cat`,
      value: 5,
      occupation: `Wonderland Resident`,
      preferences: `Alice in Wonderland; Animals; Restaurant; Nature`,
      tags: [`Story`],
      notes: `This card counts as Animal, and the character is from Wonderland.`,
    },
    {
      name: `Chief Sitting Bull`,
      value: 4,
      occupation: `Native American War Chief`,
      preferences: `-1 for General George Custer; Nature; Museum; Animals; Pest Control`,
      tags: [`Government`, `Historic`, `Wakona`],
    },
    {
      name: `Chief Thomas Grayhawk`,
      value: 8,
      occupation: `Chairman of the Wakona Nation`,
      preferences: `Wakona`,
      tags: [`Government`, `Wakona`],
    },
    {
      name: `Christopher Columbus`,
      value: 8,
      occupation: `Explorer/Sailor`,
      preferences: `Casinos; Water; Church; Sailors; Museum`,
      tags: [`Sailors`, `Historic`, `Pepperville Historic District`],
      notes: `This is a historic character, and they can arrive by time travel.`,
    },
    {
      name: `Cleopatra`,
      value: 6,
      occupation: `Ruler of Egypt`,
      preferences: `Egyptian; Jewelry; Air Conditioning; Beauty; Museum`,
      tags: [`Historic`, `Egyptian`, `Pepper Hill`],
      notes: `This is a historic character, and they can arrive by time travel.`,
    },
    {
      name: `Cierra St. Hilton`,
      value: 5,
      occupation: `Teen Heiress to multi-billion dollar fortune`,
      preferences: `Beauty; Bank; Jewelry; Retail; St. Hilton`,
      photoFile: `cierra-st-hilton.jpg`,
      tags: [`St. Hilton`, `Children`],
      notes: `This is a shared character across multiple games, and she is an accomplished artist trained by some of the finest artists in the world.`,
    },
    {
      name: `Cornelius St. Hilton`,
      value: 6,
      occupation: `Billionaire CEO`,
      preferences: `Bank; Transportation; St. Hilton`,
      tags: [`St. Hilton`, `Education`],
      notes: `This character is a part-time resident of St. Hilton, the father of Cierra St. Hilton, and the owner of St. Hilton Country Club. He also appears in The Empty Suit as an establishment Republican presidential candidate.`,
    },
    {
      name: `Debbie Deerfoot`,
      value: 2,
      occupation: `Real Estate Broker with Wakona Nation Real Estate`,
      preferences: `Real Estate; Wakona`,
      tags: [`Wakona`, `Retail`],
    },
    {
      name: `DJ Lite 2.0`,
      value: 6,
      occupation: `DJ/Record Producer`,
      preferences: `Ringwald; Music; Zoo`,
      tags: [`Ringwald`, `Retail`],
    },
    {
      name: `Easter Bunny`,
      value: 9,
      occupation: `Basket Delivery`,
      preferences: `People and things in Story; Animals; Children; Noel`,
      tags: [`Story`],
    },
    {
      name: `Flick Mulligan & Birdie Bunker`,
      value: 8,
      occupation: `#1 Blind Disc Golfer in the World`,
      preferences: `Sports; Medical; Noel; Media; Transportation`,
      notes: `These are shared recurring characters, and they also appear in The Zoo Game.`,
    },
    {
      name: `General George Custer`,
      value: 4,
      occupation: `Calvary Commander`,
      preferences: `Government; Patriotic; Story Unicorn Habitat; Transportation; -1 for Sitting Bull`,
      tags: [`Historic`],
    },
    {
      name: `George Washington`,
      value: 10,
      occupation: `President`,
      preferences: `Dentist; Patriotic; Government; Transportation; Law Enforcement`,
      tags: [`Government`, `Patriotic`, `Historic`, `Pepperville Historic District`],
      notes: `This character helps cities with dental offices.`,
    },
    {
      name: `Giuseppe Tiramisu, PhD`,
      value: 5,
      occupation: `World Renowned Cryptozoologist`,
      preferences: `Mythical; Animals; Nature; Education; Transportation`,
      notes: `This is a shared recurring character, and he also appears in The Zoo Game. He is obsessed with Ringo and Lake Ringwald.`,
    },
    {
      name: `Grant "Grandiosity" Greene`,
      value: 8,
      occupation: `Local Celebrity; Professional Wrestler`,
      preferences: `Sports; Transportation; Bank; St. Hilton; Restaurant`,
      tags: [`St. Hilton`, `Sports`, `Restaurant`],
    },
    {
      name: `Humpty Dumpty`,
      value: 6,
      occupation: `Egg Expert`,
      preferences: `-1 for Each Restaurant; People and things in Story`,
      tags: [`Story`],
      notes: `This card gives a negative preference for every restaurant in a city.`,
    },
    {
      name: `Judith Pepper`,
      value: 2,
      occupation: `Nurse`,
      preferences: `Medical`,
      notes: `This character is Jimmy Pepper's wife.`,
    },
    {
      name: `Jesse James`,
      value: -7,
      occupation: `Outlaw`,
      preferences: `Criminals; Attorneys; Casinos; Bank; Jewelry`,
      tags: [`Criminals`, `Hats`, `Pepperville Historic District`],
      notes: `This is a historic character, and they can arrive by time travel.`,
    },
    {
      name: `Jimmy Pepper`,
      value: 4,
      occupation: `Clown; Entertainer`,
      preferences: `Clown; Noel; Riverwalk; Restaurant; Casinos`,
      tags: [`Clown`, `Pepperville Riverwalk`],
      notes: `This is a shared character across multiple games. He is the son of Winfred Pepper and the grandson of Joseph Pepper.`,
    },
    {
      name: `Johnny Pepper`,
      value: 4,
      occupation: `Clown; Entertainer`,
      preferences: `Clown; Noel; Riverwalk; Restaurant; Casinos`,
      tags: [`Clown`, `Pepperville Riverwalk`],
      notes: `This is a shared character across multiple games. He is the son of Winfred Pepper, the grandson of Joseph Pepper, and a descendant of Phineas and Abigail Pepper.`,
    },
    {
      name: `Kelly Scissors`,
      value: -4,
      occupation: `Works at Story Barber Shop`,
      preferences: `Barber Shop; Beauty; Sasquatch; Mullet Man`,
    },
    {
      name: `King Tut`,
      value: 6,
      occupation: `Pharaoh`,
      preferences: `Egyptian; Museum; Noel; Air Conditioning; Jewelry`,
      tags: [`Historic`, `Egyptian`, `Hats`, `Pepper Hill`],
    },
    {
      name: `Lady Liberty`,
      value: 8,
      occupation: `Greeter`,
      preferences: `Patriotic`,
      tags: [`Patriotic`, `Historic`, `Pepperville Historic District`],
    },
    {
      name: `Loving Larry Flirt`,
      value: 2,
      occupation: `Bus Driver; Owner-Operator`,
      preferences: `Transportation; Number of Females; Music`,
      tags: [`Pepperville`, `Sports`, `Events`, `Tourist Attraction`],
      notes: `This character is also known as Loving Larry Flirt, and he is a shared character with World Tour.`,
    },
    {
      name: `Chairman Lester Ringwald`,
      value: 8,
      occupation: `Chairman, Chattawa County Board of Commissioners`,
      preferences: `Government; Media; Transportation; Events`,
      tags: [`Government`, `Ringwald`],
    },
    {
      name: `Little Red Riding Hood`,
      value: 5,
      occupation: `Food Delivery`,
      preferences: `People and things in Story; Noel; Animals; Tourist Attraction; -1 for Big Bad Wolf`,
      tags: [`Children`, `Story`],
    },
    {
      name: `Mad Hatter`,
      value: -2,
      occupation: `Hat Maker`,
      preferences: `Hats`,
      tags: [`Hats`, `Story`],
      notes: `This is a Wonderland character.`,
    },
    {
      name: `Milana`,
      value: 8,
      occupation: `Local Celebrity; Singer`,
      preferences: `Retail; Music; Beauty`,
      tags: [`St. Hilton`, `Retail`],
      notes: `This is a shared character.`,
    },
    {
      name: `Ming Wu`,
      value: 2,
      occupation: `Elf; Artist`,
      preferences: `Noel; Arts; Retail; People and things in Story; Tourist Attraction`,
      tags: [`Noel`, `Female`],
      notes: `This character lives in Noel, is shared across Pepperville and The Zoo Game, and is the artist by the Panda Exhibit in Zoo Game.`,
    },
    {
      name: `Mullet Man`,
      value: -2,
      occupation: `Mechanic`,
      preferences: `Automotive; Animals; Restaurant; Sports`,
      tags: [`Rural`],
    },
    {
      name: `Mullet Man JR.`,
      value: 3,
      occupation: `Enjoying Life`,
      preferences: `Automotive; Sports; Noel; Tourist Attraction; Mullet Man`,
      tags: [`Children`, `Rural`],
    },
    {
      name: `Napoleon Bonaparte`,
      value: -5,
      occupation: `Emperor & General`,
      preferences: `Transportation; Government; -1 for Water; French`,
      tags: [`Historic`, `French`, `Pepperville Historic District`],
      notes: `This is a historic character, and they can arrive by time travel.`,
    },
    {
      name: `Pierre Crache`,
      value: 4,
      occupation: `Restaurateur`,
      preferences: `French; Restaurant; Riverwalk; Music`,
      tags: [`French`, `Music`, `Pepperville Riverwalk`],
      notes: `This is a shared character across games. He is a co-owner of Little Paris Club, is associated with Pierre's Riverwalk Cafe, and is a musician in World Tour.`,
    },
    {
      name: `Ninja Dog`,
      value: 5,
      occupation: `Crime Fighter`,
      tags: [`Animal`, `Law Enforcement`, `Story`],
      notes: `This is a special card. All City Managers bid on it. When you win it, add 5 population to your city. It jails all negative Animal People cards in your city and keeps jailing future negative Animal People cards that appear there.`,
    },
    {
      name: `Reverend Elijah Shepherd`,
      value: 4,
      occupation: `Rector of St. Hilton Chapel`,
      preferences: `Church; Media`,
      tags: [`St. Hilton`, `Retail`, `Restaurant`],
    },
    {
      name: `Pastor Caleb Brooks`,
      value: 4,
      occupation: `Pastor of PepperChurch`,
      preferences: `Church; Media; Events`,
      tags: [`Pepperville`, `Education`, `Infrastructure`],
    },
    {
      name: `Phineas and Abigail Pepper`,
      value: 15,
      occupation: `Original settlers of Pepperville`,
      preferences: `city with the most people or places named Pepper or Pepperville`,
      tags: [`Historic`, `Pepperville Historic District`],
      notes: `These are the original settlers of Pepperville in the 1820s. Phineas arrived by wagon, built a trading post, and started the Chattawa River ferry crossing.`,
    },
    {
      name: `Chief Timothy O’Hara`,
      value: 8,
      occupation: `Police Chief of Pepperville`,
      tags: [`Government`, `Law Enforcement`, `Pepperville`],
      cardType: `special`,
      notes: `This is a special card. All City Managers bid on it. When you win it, add 8 population to your city. Once during the game, you may jail one negative People card in your city.`,
    },
    {
      name: `Queen of Hearts`,
      value: -8,
      occupation: `Queen`,
      preferences: `People and things in Story`,
      tags: [`Story`],
      notes: `This is a Wonderland character.`,
    },
    {
      name: `Ringo`,
      value: -15,
      occupation: `Legendary inhabitant of Lake Ringwald`,
      preferences: `Water`,
      tags: [`Monster`, `Ringwald`],
      notes: `This is a Lake Ringwald cryptid-like character.`,
    },
    {
      name: `Romeo Tiramisu`,
      value: -2,
      occupation: `Poet`,
      preferences: `Number of Females`,
      notes: `This character is the brother of Giuseppe and Dr. Antonio Tiramisu.`,
    },
    {
      name: `Sabre Toothed Werepanther`,
      value: -5,
      occupation: `Legendary Swamp Creature`,
      preferences: `Nature; Restaurant; Animals`,
      tags: [`Monster`, `Animal`, `Story`],
      notes: `This is a negative Animal People card, and the character has a Wonderland-adjacent mythical style.`,
    },
    {
      name: `Santa Claus`,
      value: 25,
      occupation: `Santa`,
      preferences: `Noel; Tourist Attraction; Number of Children; Animals`,
      tags: [`Noel`, `Retail`],
      notes: `This character is a resident of Noel and a shared character across games.`,
    },
    {
      name: `Sasquatch`,
      value: -5,
      occupation: `Legendary Creature of the Forest`,
      preferences: `Nature; Restaurant`,
      tags: [`Monster`, `Animal`],
      notes: `This is a negative Animal People card.`,
    },
    {
      name: `Savannah Pierce`,
      value: 5,
      occupation: `TV News Reporter - WPEP Channel 7`,
      preferences: `Media; Local Celebrities; Government; Tourist Attraction; Beauty`,
      tags: [`Pepperville`, `Organization`],
    },
    {
      name: `Condaleeza Steele`,
      value: 8,
      occupation: `World Champion in Modern Pentathlon`,
      preferences: `Sports; Local Celebrities; Media; Patriotic; Church`,
      tags: [`Sports`],
      notes: `This character is the daughter of presidential candidate Monica Steele. She grew up in South Carolina, lives in Pepperville, and her photo is at PepperChurch.`,
    },
    {
      name: `Sheriff Clay Maddox`,
      value: 8,
      occupation: `Sheriff of Chattawa County`,
      tags: [`Government`, `Law Enforcement`, `Rural`],
      cardType: `special`,
      notes: `This is a special card. All City Managers bid on it. When you win it, add 8 population to your city. Once during the game, you may jail one negative People card in your city.`,
    },
    {
      name: `Skel-O-Dude`,
      value: 8,
      occupation: `Musician/Entertainer`,
      preferences: `Retail; Amusement Park; Music; Restaurant; Tourist Attraction`,
      tags: [`Story`],
    },
    {
      name: `The Hatley Family`,
      value: 12,
      occupation: `Family of 12`,
      preferences: `Medical; Transportation; Events; Riverwalk; Tourist Attraction`,
      childrenCount: 8,
      tags: [`Children`, `Pepperville Riverwalk`],
      notes: `This card was renamed from The Reilly Family.`,
    },
    {
      name: `The Tooth Fairy`,
      value: 5,
      occupation: `In the Dental Field`,
      preferences: `Dentist; Sports; George Washington; Children; Bank`,
      tags: [`Story`],
    },
    {
      name: `Thomas Edison`,
      value: 8,
      occupation: `Inventor`,
      preferences: `Chattawa Valley EMC; Chattawa Valley Reactor; Library; Transportation; Media`,
      tags: [`Historic`, `Pepperville Historic District`],
    },
    {
      name: `Tiffany Ringwald`,
      value: 4,
      occupation: `Singer; Dog Groomer`,
      preferences: `Ringwald; Music; Animals; Retail; Media`,
      tags: [`Ringwald`, `Real Estate`],
      notes: `This is a shared character across multiple games and the aunt of Tina Ringwald.`,
    },
    {
      name: `Tina Ringwald`,
      value: 3,
      occupation: `Kid`,
      preferences: `Amusement Park; Noel; Animals; Retail; Tourist Attraction`,
      tags: [`Children`, `Ringwald`, `Noel`],
      notes: `This character is the niece of Tiffany Ringwald.`,
    },
    {
      name: `Trish “Poodle Girl” Alfonzo`,
      value: 2,
      occupation: `Local Celebrity`,
      preferences: `Music; Animals; Beauty`,
      tags: [`Pepperville`, `Automotive`],
      notes: `This character is married to Elvis Alfonzo.`,
    },
    {
      name: `Wesley Sharp`,
      value: 6,
      occupation: `Chattawa County Communications Director`,
      preferences: `Media; Government; Law Enforcement; Courthouse; Local Celebrities`,
      tags: [`Pepperville`],
    },
    {
      name: `Wicked Jim DeVito`,
      value: -10,
      occupation: `Godfather`,
      preferences: `Criminals; Casinos; Bank; Attorneys; Jewelry`,
      tags: [`Criminals`],
      notes: `This is a shared character, and she also appears in the music world.`,
    },
    {
      name: `Wilfred Pepper`,
      value: 3,
      occupation: `Bartender at the Zoo`,
      preferences: `Restaurant; Music; Automotive`,
      notes: `This is a shared character across multiple games.`,
    },
  ],
  businesses: [
    {
      name: `Wicked Jim's Storage`,
      value: 4,
      revenue: `56+ = 1R; 30-55 = 0R; 0-29 = -1R`,
      tags: [`Pepper Hill`],
      notes: `This business is owned by Wicked Jim DeVito, who wanted his own personal storage company.`,
    },
    {
      name: `LaDiva Dance Studio`,
      value: 4,
      revenue: `41+ = 1R; 26-40 = 0R; 0-25 = -1R`,
      tags: [`St. Hilton`],
      notes: `This is a dance studio in St. Hilton.`,
    },
    {
      name: `Bumbles the Magician`,
      value: 3,
      revenue: `0R`,
      cardType: `special`,
      occupation: `Will the trick work or backfire?`,
      notes: `This is a special card. All City Managers bid on it. When you win it, choose an opponent and attempt Bumbles' trick. If it succeeds, steal that city's highest-value card and any matching people. If it fails, one of your cards will be given to that city at random, along with any matching people.`,
    },
    {
      name: `Pepperville Regional Airport`,
      value: 30,
      revenue: `190+ = 1R; 130-189 = 0R; 101-129 = -1R; 50-100 = -2R; 0-49 = -3R`,
      tags: [`Pepperville`, `Transportation`],
      notes: `This is an airport.`,
    },
    {
      name: `Ale & Freedom Tavern`,
      value: 5,
      revenue: `61+ = 1R; 41-60 = 0R; 0-40 = -1R`,
      tags: [`Patriotic`, `Restaurant`, `Pepperville Historic District`],
      notes: `This is a tavern, bar, and restaurant.`,
    },
    {
      name: `Pepperville Movers`,
      value: 3,
      revenue: `70+ = 1R; 40-69 = 0R; 0-39 = -1R`,
      tags: [`Pepperville`, `Movers`, `Real Estate`],
      notes: `This is a moving company. When you win this card, choose a player and move one business or people card from that player's city to yours immediately.`,
    },
    {
      name: `Phineas Pepper Amphitheater`,
      value: 5,
      revenue: `-1R per turn`,
      tags: [`Pepperville Historic District`, `Music`, `Events`, `Infrastructure`],
      notes: `If you have a restaurant in the Pepperville Historic District, then the revenue is 0R instead of -1R in your city.`,
    },
    {
      name: `Coolwater Heating & Air`,
      value: 3,
      revenue: `100+ = 1R; 50-99 = 0R; 0-49 = -1R`,
      tags: [`Pepperville`, `Air Conditioning`],
      notes: `This business is operated by Curtis Coolwater.`,
    },
    {
      name: `The Galleria at St. Hilton`,
      value: 25,
      revenue: `150+ = 3R; 110-149 = 2R; 90-109 = 1R; 70-89 = -1R; 50-69 = -2R; 1-49 = -3R`,
      tags: [`St. Hilton`],
      notes: `This is a mall.`,
    },
    {
      name: `Chattawa and Western Railroad`,
      value: 20,
      revenue: `150+ = 3R; 110-149 = 2R; 90-109 = 1R; 70-89 = -1R; 50-69 = -2R; 1-49 = -3R`,
      tags: [`Transportation`, `Pepperville`],
      notes: `This railroad provides passenger service to five states in the region.`,
    },
    {
      name: `Cierra's Boutique`,
      value: 4,
      revenue: `51+ = 1R; 30-50 = 0R; 0-29 = -1R`,
      tags: [`St. Hilton`, `Retail`],
      notes: `This business is owned by multi-billion-dollar teen heiress Cierra St. Hilton.`,
    },
    {
      name: `St. Hilton Diamond Mine`,
      value: 4,
      revenue: `176+ = 2R; 101-175 = 1R; 51-100 = 0R; 0-50 = -1R`,
      tags: [`St. Hilton`],
      notes: `This is a diamond mine.`,
    },
    {
      name: `Riverview Salon and Spa`,
      value: 6,
      revenue: `40+ = 1R; 26-39 = 0R; 0-25 = -1R`,
      tags: [`Water`, `Pepperville Riverwalk`, `Beauty`],
      notes: `This is a salon and spa.`,
    },
    {
      name: `Chattawa Smile Center`,
      value: 4,
      revenue: `150+ = 2R; 91-149 = 1R; 60-90 = 0R; 0-59 = -1R`,
      tags: [`Dental`, `Pepperville`],
      notes: `If George Washington is in your city, add 1R to this card's revenue.`,
    },
    {
      name: `Pepperville Poblanos`,
      value: 15,
      revenue: `150+ = 2R; 100-149 = 1R; 70-99 = 0R; 40-69 = -1R; 0-39 = -2R`,
      tags: [`Pepperville`],
      notes: `This is a minor league baseball team.`,
    },
    {
      name: `Pepperville Book Warehouse`,
      value: 15,
      revenue: `120+ = 2R; 80-119 = 1R; 60-79 = 0R; 40-59 = -1R; 30-39 = -2R; 1-29 = -3R`,
      tags: [`Pepperville`],
      notes: `This is a book warehouse located in Pepper Place Mall.`,
    },
    {
      name: `Lake Ringwald Christian School`,
      value: 8,
      revenue: `130+ = 2R; 80-129 = 1R; 61-79 = 0R; 41-60 = -1R; 0-40 = -2R`,
      tags: [`Ringwald`, `Water`, `Church`, `Education`],
      notes: `This school prepares future leaders with a spiritual foundation and serves grades K-12.`,
    },
    {
      name: `Chattawa County Chamber of Commerce`,
      value: 10,
      revenue: `9+ = 2R; 6-8 = 1R; 3-5 = 0R; 0-2 = -1R`,
      tags: [`Organization`, `Pepperville`],
      notes: `This is the Chamber of Commerce.`,
    },
    {
      name: `Pepperville Pest Eliminators`,
      value: 3,
      revenue: `50+ = 1R; 20-49 = 0R; 0-19 = -1R`,
      tags: [`Pepperville`],
      notes: `This business protects the city from Giant Spider Attack.`,
    },
    {
      name: `Riverwalk Dental Associates`,
      value: 4,
      revenue: `150+ = 2R; 91-149 = 1R; 60-90 = 0R; 0-59 = -1R`,
      tags: [`Water`, `Dental`, `Pepperville Riverwalk`],
      notes: `If George Washington is in your city, add 1R to this card's revenue.`,
    },
    {
      name: `Chattawa Valley Times`,
      value: 10,
      revenue: `0R`,
      tags: [`Media`, `Pepperville Historic District`],
      notes: `This is a one-time event. The next business that opens in your city is featured in the paper. A positive business adds 5 population, and a negative business causes you to lose 5 additional population.`,
    },
    {
      name: `WPEP - Channel 7`,
      value: 12,
      revenue: `-1R per turn`,
      tags: [`Media`, `Pepperville`],
      notes: `This is a television station and news channel.`,
    },
    {
      name: `Old Wakona Village`,
      value: 15,
      revenue: `0-60 = -2R; 61-90 = -1R; 91-110 = 0R; 111-135 = 1R; 136-160 = 2R; 161+ = 3R`,
      tags: [`Wakona`, `Tourist Attraction`],
      notes: `This tourist attraction recreates life in the Wakona region during the 1800s. Visitors can explore authentic-looking lodges and teepees, watch traditional craft demonstrations, enjoy cultural performances, and shop for handmade goods while surrounded by beautiful mountain scenery. Designed as a family-friendly destination, the village blends history, entertainment, and local heritage into one of Wakona's most visited attractions.`,
    },
    {
      name: `The Chattawa Cone`,
      value: 10,
      revenue: `181+ = 2R; 121-180 = 1R; 100-120 = 0R; 51-99 = -1R; 0-50 = -2R`,
      tags: [`Tourist Attraction`, `Restaurant`, `Pepperville Riverwalk`],
      notes: `This is an ice cream shop.`,
    },
    {
      name: `Mulligan's Disc Golf Supply`,
      value: 4,
      revenue: `45+ = 1R; 25-44 = 0R; 0-24 = -1R`,
      tags: [`Retail`, `Sports`, `Pepperville Riverwalk`],
      notes: `This is a disc golf supply shop on the Riverwalk, and it is owned by Flick Mulligan.`,
    },
    {
      name: `Callahan Hardware`,
      value: 8,
      revenue: `91+ = 1R; 71-90 = 0R; 0-70 = -1R`,
      tags: [`Retail`, `Pepperville`],
      notes: `This business is owned by Duke Callahan.`,
    },
    {
      name: `Chattawa County Courthouse`,
      value: 18,
      revenue: `-1R`,
      tags: [`Government`, `Courthouse`, `Pepperville Historic District`],
      notes: `This is the courthouse.`,
    },
    {
      name: `Story City Hall`,
      value: 6,
      revenue: `60+ = 1R; 0-59 = -1R`,
      tags: [`Story`, `Government`],
      notes: `This is the city hall for the Story district.`,
    },
    {
      name: `Pepperville Arts Center`,
      value: 12,
      revenue: `-1R`,
      tags: [`Pepperville`],
      notes: `This is an arts center.`,
    },
    {
      name: `Wakona Trading Company`,
      value: 5,
      revenue: `60+ = 1R; 40-59 = 0R; 0-39 = -1R`,
      tags: [`Wakona`, `Tourist Attraction`, `Sports`],
      notes: `This is a trading company in Wakona Nation.`,
    },
    {
      name: `Chattawa Valley Convention & Visitors Bureau`,
      value: 12,
      revenue: `-R per turn`,
      tags: [`Tourist Attraction`, `Pepperville Riverwalk`],
      notes: `The winning bidder may draw from the main deck until a People card is drawn. Add that People card to the city and discard the rest.`,
    },
    {
      name: `Chattawa Valley History Museum`,
      value: 15,
      revenue: `141+ = 1R; 81-140 = 0R; 0-80 = -1R`,
      tags: [`Historic`, `Tourist Attraction`, `Pepperville Historic District`],
      notes: `This museum is home to the oldest structure in Chattawa County, circa 1820.`,
    },
    {
      name: `Ringwald Rid-A-Pest`,
      value: 3,
      revenue: `50+ = 1R; 20-49 = 0R; 0-19 = -1R`,
      tags: [`Ringwald`, `Pest Control`],
      notes: `This business protects the city from Giant Spider Attack.`,
    },
    {
      name: `640 The CHATT Talk`,
      value: 12,
      revenue: `100+ = 2R; 60-99 = 1R; 30-59 = 0R; 0-29 = -1R`,
      tags: [`Media`, `Pepperville Riverwalk`],
      photoFile: `640-the-chatt.jpg`,
      notes: `This radio station serves the Chattawa Valley with news and information.`,
    },
    {
      name: `Chattawa River Adventures`,
      value: 8,
      revenue: `60+ = 1R; 40-59 = 0R; 0-39 = -1R`,
      tags: [`Water`, `Tourist Attraction`, `Rural`],
      notes: `Located near Pepper Hill, it provides whitewater rafting, canoe, and kayak adventures.`,
    },
    {
      name: `Chattawa Valley News & Views`,
      value: 10,
      revenue: `special`,
      photoFile: `chattawa-valley-news-and-views.jpg`,
      tags: [`Pepperville`, `Media`],
      notes: `This is a one-time event. The next business that opens in your city is featured in the magazine. A positive business adds 5 population, and a negative business causes you to lose 5 additional population.`,
    },
    {
      name: `Foothills Women's Center`,
      value: 5,
      revenue: `special`,
      tags: [`Pepperville`],
      notes: `Once your population is over 50, this business generates $2 per turn for each female in your city, up to a maximum of $20.`,
    },
    {
      name: `Pepperville Eye Clinic`,
      value: 5,
      revenue: `150+ = 2R; 90-149 = 1R; 50-89 = 0R; 31-49 = -1R; 0-30 = -2R`,
      tags: [`Medical`, `Pepperville`],
      notes: `This is an eye clinic tied to Dr. Chen Wu.`,
    },
    {
      name: `FirstBank of Chattawa`,
      value: 10,
      revenue: `special`,
      tags: [`Pepperville`],
      notes: `This card gives you $1 for every 20 people in your city each turn when calculating revenue.`,
    },
    {
      name: `Noel Toy Shop`,
      value: 4,
      revenue: `150+ = 2R; 91-149 = 1R; 60-90 = 0R; 0-59 = -1R`,
      tags: [`Noel`, `Retail`],
      notes: `This is a toy shop in Noel.`,
    },
    {
      name: `Flirt's Celebrity Bus Tours`,
      value: 4,
      revenue: `41+ = 1R; 26-40 = 0R; 0-25 = -1R`,
      tags: [`Tourist Attraction`, `Pepperville Riverwalk`],
      notes: `Loving Larry Flirt takes guests to see the homes of the rich and famous, including Grant Greene, Milana, LaDiva, Miss Pearl, Elvis Alfonzo, and Poodle Girl.`,
    },
    {
      name: `Lake Ringwald`,
      value: 7,
      revenue: `special`,
      tags: [`Ringwald`, `Water`, `Tourist Attraction`, `Nature`],
      notes: `This card is worth +7 now and adds 1 per turn.`,
    },
    {
      name: `Americana Diner`,
      value: 12,
      revenue: `110+ = 2R; 60-109 = 1R`,
      tags: [`Restaurant`, `Pepperville`],
      notes: `This diner serves burgers, breakfast all day, and Mile High Cherry Pie.`,
    },
    {
      name: `Chattawa Technical College`,
      value: 20,
      revenue: `130+ = 2R; 86-129 = 1R; 66-85 = 0R; 51-65 = -1R; 36-50 = -2R; 0-35 = -3R`,
      tags: [`Education`, `Pepperville`],
      notes: `This is a college.`,
    },
    {
      name: `Carl's Truckstop`,
      value: 4,
      revenue: `61+ = 1R; 40-60 = 0R; 0-39 = -1R`,
      tags: [`Automotive`, `Restaurant`, `Rural`],
      notes: `This is a 24-hour truckstop and restaurant off the interstate.`,
    },
    {
      name: `Bigfoot Shoes`,
      value: 4,
      revenue: `80+ = 1R; 50-79 = 0R; 0-49 = -1R`,
      tags: [`Retail`, `Ringwald`],
      notes: `This shop sells shoes and hiking accessories.`,
    },
    {
      name: `Day Spa at St. Hilton`,
      value: 6,
      revenue: `60+ = 1R; 50-59 = 0R; 0-49 = -1R`,
      tags: [`St. Hilton`],
      notes: `This is a day spa for the wealthiest residents of St. Hilton.`,
    },
    {
      name: `Chattawa Valley EMC`,
      value: 25,
      revenue: `140+ = 2R; 100-139 = 1R; 80-99 = 0R; 50-79 = -1R; 40-49 = -2R; 0-39 = -3R`,
      tags: [`Infrastructure`, `Pepperville`],
      notes: `This utility powers the Chattawa Valley with clean and affordable electricity.`,
    },
    {
      name: `Little Paris Club`,
      value: 10,
      revenue: `130+ = 2R; 60-129 = 1R; 40-59 = 0R; 0-39 = -1R`,
      tags: [`French`, `Music`, `Restaurant`, `Pepperville`, `Tourist Attraction`],
      notes: `This is a popular French-themed club and restaurant owned by Pierre Crache. Its Eiffel Tower is a popular photo opportunity.`,
    },
    {
      name: `Nostalgia`,
      value: 10,
      revenue: `110+ = 2R; 80-109 = 1R; 60-79 = 0R; 30-59 = -1R; 0-29 = -2R`,
      tags: [`Restaurant`, `Pepperville Historic District`],
      notes: `This is a Cajun cafe.`,
    },
    {
      name: `Crusty's Place`,
      value: 10,
      revenue: `120+ = 2R; 60-119 = 1R; 40-59 = 0R; 0-39 = -1R`,
      tags: [`Restaurant`, `Pepperville`],
      notes: `This is a popular Texas-style club featuring live music and good times.`,
    },
    {
      name: `Pepper Hill Winery`,
      value: 4,
      revenue: `60+ = 1R; 40-59 = 0R; 0-39 = -1R`,
      tags: [`Pepper Hill`, `Wine`, `Tourist Attraction`],
      notes: `This is a winery owned by Wilfred Pepper and located in the Pepper Hill section of Chattawa County.`,
    },
    {
      name: `Paws by Tiffany`,
      value: 3,
      revenue: `30+ = 1R; 11-29 = 0R; 1-10 = -1R`,
      tags: [`Ringwald`],
      notes: `This is a pet grooming and sitting business owned by local music celebrity Tiffany Ringwald.`,
    },
    {
      name: `Phineas & Abigail Pepper Statue`,
      value: 5,
      revenue: `0+ = 0R`,
      tags: [`Historic`, `Pepperville Historic District`],
      notes: `This statue attracts 5 people.`,
    },
    {
      name: `Waffle Master`,
      value: 10,
      revenue: `61+ = 1R; 40-60 = 0R; 0-39 = -1R`,
      tags: [`Restaurant`, `Pepperville`],
      notes: `The Valley's Favorite Breakfast!`,
    },
    {
      name: `Chattawa Valley High School`,
      value: 15,
      revenue: `-1R per turn`,
      tags: [`Pepperville`],
      notes: `This is home of the Riverhawks.`,
    },
    {
      name: `Chattawa Valley Mortgage Co.`,
      value: 4,
      revenue: `36+ = 1R; 21-35 = 0R; 0-20 = -1R`,
      tags: [`Pepperville`],
      notes: `This is a mortgage office.`,
    },
    {
      name: `Pepperville Women's Club`,
      value: 4,
      revenue: `special`,
      tags: [`Pepperville`],
      notes: `This is a community organization.`,
    },
    {
      name: `Smiley Rent-A-Car`,
      value: 3,
      revenue: `41+ = 1R; 30-40 = 0R; 1-29 = -1R`,
      tags: [`Pepperville`],
      notes: `This is a rental car business owned by Buzz Smiley.`,
    },
    {
      name: `Pepperville AutoMall`,
      value: 12,
      revenue: `130+ = 2R; 80-129 = 1R; 60-79 = 0R; 30-59 = -1R; 0-29 = -2R`,
      tags: [`Pepperville`],
      notes: `This is a huge new and used car dealership owned by Buzz Smiley.`,
    },
    {
      name: `Chattawa Riverwalk`,
      value: 15,
      revenue: `-1R per turn`,
      tags: [`Water`, `Tourist Attraction`, `Pepperville Riverwalk`],
      notes: `This is a hub of shops and restaurants on the Chattawa River in downtown Pepperville.`,
    },
    {
      name: `Pepper Zoological Park`,
      value: 25,
      revenue: `151+ = 1R; 121-150 = 0R; 91-120 = -1R; 61-90 = -2R; 0-60 = -3R`,
      tags: [`Animal`, `Tourist Attraction`, `Pepper Hill`],
      notes: `This zoo is world-famous for its cryptids and dinosaurs, in addition to its wide selection of animals.`,
    },
    {
      name: `Chattawa Insurance Agency`,
      value: 3,
      revenue: `40+ = 1R; 0-39 = -1R`,
      tags: [`Insurance`],
      photoFile: `chattawa-insurance-agency.jpg`,
      notes: `This insurance card protects the city in which it is located from disaster-style cards such as Giant Spider Attack.`,
    },
    {
      name: `The Law Office of Ash Bandicott`,
      value: 4,
      revenue: `40+ = 1R; 0-39 = -1R`,
      tags: [`Pepperville Historic District`, `Attorney`],
      notes: `This law firm is led by Ash Bandicott, and it gets an extra 1R if it is in the same city as the Courthouse.`,
    },
    {
      name: `Ringwald Realty`,
      value: 4,
      revenue: `31+ = 1R; 0-30 = -1R`,
      tags: [`Ringwald`],
      notes: `This is a realty office.`,
    },
    {
      name: `Ringwald Cosmetics & Gifts`,
      value: 8,
      revenue: `70+ = 1R; 50-69 = 0R; 0-49 = -1R`,
      tags: [`Ringwald`],
      notes: `This is a cosmetic studio.`,
    },
    {
      name: `Miss Pearl's Sweet Shop`,
      value: 5,
      revenue: `150+ = 2R; 30-149 = 1R; 20-29 = 0R; 0-19 = -1R`,
      tags: [`Pepperville Riverwalk`],
      notes: `This sweet shop is home to the world-famous Lost Your Mind Pralines. Meet Miss Pearl.`,
    },
    {
      name: `CommunityVerse Medical Pavilion`,
      value: 8,
      revenue: `special`,
      tags: [`Medical`, `Pepperville`],
      notes: `This card adds +1R per turn for every medical and dental practice and pharmacy in the city.`,
    },
    {
      name: `CommunityVerse Medical Center`,
      value: 18,
      revenue: `200+ = 2R; 150-199 = 1R; 100-149 = 0R; 60-99 = -1R; 0-59 = -2R`,
      photoFile: `communityverse-medical-center.jpg`,
      tags: [`Medical`, `Pepperville`],
      notes: `This is the CommunityVerse region's largest hospital, providing top-level care to the Chattawa Valley.`,
    },
    {
      name: `Pierre's Riverwalk Cafe`,
      value: 3,
      revenue: `150+ = 2R; 90-149 = 1R; 51-89 = 0R; 30-50 = -1R; 1-29 = -2R`,
      tags: [`Water`, `French`, `Restaurant`, `Pepperville Riverwalk`],
      notes: `This is a Riverwalk cafe owned by Pierre Crache from the Music Game.`,
    },
    {
      name: `Pepperville Public Library`,
      value: 15,
      revenue: `101+ = -2R; 0-100 = -1R`,
      tags: [`Pepperville`],
      notes: `This is a library system.`,
    },
    {
      name: `Patel Family Pharmacy`,
      value: 8,
      revenue: `130+ = 2R; 60-129 = 1R; 40-59 = 0R; 30-39 = -1R; 0-29 = -2R`,
      tags: [`Medical`, `Pepperville`],
      notes: `This is a pharmacy owned by Josh Patel.`,
    },
    {
      name: `PepperChurch`,
      value: 15,
      revenue: `special`,
      tags: [`Pepperville`, `Church`],
      notes: `PepperChurch is the largest house of worship in Chattawa County.`,
    },
    {
      name: `St. Hilton Chapel`,
      value: 12,
      revenue: `special`,
      photoFile: `st-hilton-chapel.jpg`,
      tags: [`St. Hilton`, `Church`, `Historic`, `Tourist Attraction`],
      notes: `This is a historic church and a well-known chapel visible in CVB photography.`,
    },
    {
      name: `St. Hilton Academy`,
      value: 6,
      revenue: `50+ = 1R; 25-49 = 0R; 0-24 = -1R`,
      tags: [`St. Hilton`],
      notes: `This is an academy.`,
    },
    {
      name: `Chattawa Valley Reactor`,
      value: -20,
      revenue: `1R per turn`,
      tags: [`Rural`],
      notes: `Fear of fallout from the Chattawa Valley Reactor causes a one-time loss of 20 population in the city where it is placed, plus 5 population in the other two cities.`,
    },
    {
      name: `Chattawa Valley Recreation Area`,
      value: 20,
      revenue: `-1R per turn`,
      tags: [`Tourist Attraction`, `Nature`, `Ringwald`],
      notes: `This card attracts one additional resident each turn throughout the entire game.`,
    },
    {
      name: `Fairytale Lake & Forest`,
      value: 7,
      revenue: `special`,
      cardType: `special`,
      occupation: `+7 now and +1 Per Round`,
      tags: [`Nature`, `Story`, `Tourist Attraction`],
      notes: `The winning bidder gains 7 people immediately, plus 1 person at the end of each turn for the rest of the game.`,
    },
    {
      name: `Pity Fairy`,
      value: 0,
      revenue: `special`,
      cardType: `special`,
      occupation: `+5 per turn for the Most Pitiful City`,
      photoFile: `the-pity-fairy.jpg`,
      notes: `At the end of each round, the Pity Fairy adds 5 population to the city in last place. If multiple cities are tied for last place population, the Pity Fairy breaks the tie by choosing the tied city with the lowest cash.`,
    },
    {
      name: `Giant Spider Attack`,
      value: 0,
      revenue: `special`,
      cardType: `special`,
      occupation: `Play on a Rival City`,
      photoFile: `giant-spider-attack.jpg`,
      notes: `The winning bidder sends the Giant Spider to any city. At the end of each round, the city with the Spider may pay $75 to destroy it before the roll. Otherwise, roll 2d6. A 7 or doubles destroy the Spider. If not, it removes one random business from that city. Insurance, safety, and spider protection cards destroy it immediately.`,
    },
    {
      name: `Blind Luck`,
      value: 0,
      revenue: `special`,
      cardType: `special`,
      occupation: `Buy a Card for $20`,
      notes: `When drawn, each player in order may purchase the top card in the draw pile, sight unseen, for $20.`,
    },
    {
      name: `Boom Times`,
      value: 0,
      revenue: `special`,
      cardType: `special`,
      occupation: `Two Cards for Everyone`,
      photoFile: `boom-times.jpg`,
      notes: `When revealed, each city receives two cards from the top of the deck, drawn one by one in player order.`,
    },
    {
      name: `Taste of Pepperville`,
      value: 6,
      revenue: `special`,
      cardType: `special`,
      specialSubtype: `festival`,
      photoFile: `taste-of-pepperville.jpg`,
      occupation: `Food festival at the Chattawa County Fairgrounds`,
      tags: [`Events`, `Restaurant`],
    },
    {
      name: `Chattawa County Fair`,
      value: 10,
      revenue: `special`,
      cardType: `special`,
      specialSubtype: `festival`,
      photoFile: `chattawa-county-fair.jpg`,
      occupation: `County fair at the Chattawa County Fairgrounds`,
      tags: [`Events`, `Tourist Attraction`, `Rural`],
    },
    {
      name: `Grant Greene's Wrestling School`,
      value: 6,
      revenue: `16+ = 1R; 0-15 = -1R`,
      tags: [`St. Hilton`],
      notes: `Aspiring wrestlers from the region receive training from this wrestling superstar.`,
    },
    {
      name: `Poorly Maintained Pool`,
      value: -10,
      revenue: `-1R per turn`,
      cardType: `special`,
      occupation: `-1R/Turn - Play on a Rival City`,
      photoFile: `poorly-maintained-pool.jpg`,
      notes: `The winning bidder may place this poorly maintained pool in another player's city. That city loses 10 population and 1R per turn.`,
    },
    {
      name: `Noel 365 Amusement Park`,
      value: 20,
      revenue: `150+ = 2R; 100-149 = 1R; 60-99 = 0R; 30-59 = -1R; 0-29 = -2R`,
      tags: [`Noel`, `Tourist Attraction`],
      notes: `This is a Christmas theme park drawing visitors from around the world.`,
    },
    {
      name: `Wakona Heritage Museum`,
      value: 15,
      revenue: `151+ = 1R; 81-150 = 0R; 0-80 = -1R`,
      tags: [`Wakona`, `Tourist Attraction`],
      notes: `This is a museum.`,
    },
    {
      name: `Princess Cierra Party Shop`,
      value: 5,
      revenue: `50+ = 1R; 30-49 = 0R; 0-29 = -1R`,
      tags: [`St. Hilton`],
      notes: `This shop handles princess parties, is located in St. Hilton, and is owned by Cierra St. Hilton.`,
    },
    {
      name: `Time Travel Terminal`,
      value: 12,
      revenue: `150+ = 1R; 100-149 = 0R; 60-99 = -1R; 0-59 = -2R`,
      tags: [`Transportation`, `Historic`, `Pepperville Historic District`],
      notes: `This terminal serves Time Travel Tours. The company provides time travel services using Amish-style buggies and explains how historic characters arrive in Pepperville.`,
    },
    {
      name: `Santa's Noel Workshop`,
      value: 12,
      revenue: `-1R per turn`,
      tags: [`Noel`],
      notes: `This card adds +1R each for Santa, Rent-A-Elf, or any elves that come to your city.`,
    },
    {
      name: `Chattawa Learning Center`,
      value: 6,
      revenue: `50+ = 1R; 25-49 = 0R; 0-24 = -1R`,
      tags: [`Education`, `Pepperville`],
      notes: `This learning center serves ages 2 through K5 with an advanced learning curriculum.`,
    },
    {
      name: `Valley Shield Insurance`,
      value: 3,
      revenue: `40+ = 1R; 0-39 = -1R`,
      tags: [`Insurance`, `Pepperville`],
      notes: `This insurance card is owned by Rick Romano, the brother of Mayor Joyce Romano Pepper. It protects the city in which it is located from disaster-style cards such as Giant Spider Attack.`,
    },
    {
      name: `House of Milana`,
      value: 5,
      revenue: `70+ = 1R; 50-69 = 0R; 0-49 = -1R`,
      tags: [`St. Hilton`],
      notes: `This is a formalwear business in St. Hilton. It is owned by Milana, though she is not there very much.`,
    },
    {
      name: `Pepper Place Mall`,
      value: 5,
      revenue: `100+ = 2R; 0-99 = -2R`,
      tags: [`Pepperville`],
      notes: `Pepper Place Mall is Pepperville's main shopping center, with department stores, specialty shops, and a food court.`,
    },
    {
      name: `Rent-A-Elf`,
      value: 5,
      revenue: `100+ = 2R; 0-99 = -2R`,
      tags: [`Noel`],
      notes: `This is an elf rental service owned by Ming Wu, who sometimes goes by Ming Wu Elf.`,
    },
    {
      name: `Firehouse Cafe`,
      value: 10,
      revenue: `96+ = 2R; 51-95 = 1R; 30-50 = -1R; 1-29 = -2R`,
      tags: [`Restaurant`, `Pepperville Historic District`],
      notes: `This is a restaurant and small club in a restored historic firehouse from the early 1900s.`,
    },
    {
      name: `Ming Ming Stables`,
      value: 4,
      revenue: `150+ = 2R; 91-149 = 1R; 60-90 = 0R; 0-59 = -1R`,
      tags: [`Animal`, `Ringwald`],
      notes: `This is a horse rental stable in Ringwald, and it is owned by singer Jensing.`,
    },
    {
      name: `Ringo's Monster Emporium`,
      value: 3,
      revenue: `51+ = 1R; 31-50 = 0R; 0-30 = -1R`,
      photoFile: `ringos-monster-emporium.jpg`,
      tags: [`Ringwald`, `Water`, `Retail`],
      notes: `This is a river monster emporium located by Lake Ringwald.`,
    },
    {
      name: `Ringwald Marina`,
      value: 6,
      revenue: `70+ = 1R; 30-69 = 0R; 0-29 = -1R`,
      photoFile: `ringwald-marina.jpg`,
      tags: [`Ringwald`, `Water`, `Transportation`],
      notes: `This is a marina on Lake Ringwald with boat slips and dock access.`,
    },
    {
      name: `Chang's Grill`,
      value: 10,
      revenue: `51+ = 1R; 35-50 = 0R; 0-34 = -1R`,
      tags: [`Restaurant`, `Pepperville`],
      notes: `This is a neighborhood Chinese restaurant. It is also featured in World Tour.`,
    },
    {
      name: `The Tipsy Frog`,
      value: 10,
      revenue: `151+ = 2R; 100-150 = 1R; 51-99 = 0R; 0-50 = -1R`,
      tags: [`Restaurant`, `Pepperville`],
      notes: `This is a restaurant and 3,000-seat music venue. It is also in the Music Game.`,
    },
    {
      name: `Chattawa Speedway`,
      value: 20,
      revenue: `150+ = 1R; 100-149 = 0R; 70-99 = -1R; 40-69 = -2R; 1-39 = -3R`,
      tags: [`Sports`, `Events`, `Tourist Attraction`, `Rural`],
      notes: `This is a speedway.`,
    },
    {
      name: `Sockhops`,
      value: 10,
      revenue: `111+ = 2R; 71-110 = 1R; 51-70 = 0R; 30-50 = -1R; 0-29 = -2R`,
      tags: [`Restaurant`, `Pepperville`],
      notes: `This is a pizza restaurant and a venue in the Music Game as well.`,
    },
    {
      name: `Sweet Holly's Candy & Fudge`,
      value: 5,
      revenue: `40+ = 1R; 30-39 = 0R; 0-29 = -1R`,
      tags: [`Noel`],
      notes: `This is a candy company in Noel.`,
    },
    {
      name: `Pepper Hill Sphinx`,
      value: 10,
      revenue: `special`,
      tags: [`Mythical`, `Egyptian`, `Tourist Attraction`, `Pepper Hill`],
      notes: `This attraction is located in Pepper Hill overlooking Riverside Parkway and the Chattawa River. In 1978, a wealthy developer planned an Egyptian-themed attraction that never happened. The Sphinx remains a beloved landmark and tourist attraction.`,
    },
    {
      name: `PepperCade`,
      value: 10,
      revenue: `60+ = 1R; 41-59 = 0R; 0-40 = -1R`,
      tags: [`Water`, `Tourist Attraction`, `Restaurant`, `Pepperville Riverwalk`],
      notes: `This is a retro arcade, pizza, and music venue on the Riverwalk.`,
    },
    {
      name: `Trivia by Dylan`,
      value: 5,
      revenue: `special`,
      notes: `This card adds +1R to each restaurant in your city, up to a maximum value of +2R.`,
    },
    {
      name: `Grand Wakona Resort & Casino`,
      value: 15,
      revenue: `120+ = 2R; 60-119 = 1R; 40-59 = 0R; 20-39 = -1R; 0-19 = -2R`,
      tags: [`Wakona`, `Tourist Attraction`],
      notes: `This world-famous attraction is one of the largest businesses in Chattawa County, and it provides the Wakona Nation with a valuable source of revenue.`,
    },
    {
      name: `Nails on the Riverwalk`,
      value: 3,
      revenue: `30+ = 1R; 20-29 = 0R; 0-19 = -1R`,
      tags: [`Water`, `Pepperville Riverwalk`, `Beauty`],
      notes: `This is a popular nail studio with a view of the Chattawa River.`,
    },
    {
      name: `Chattawa Bridge`,
      value: 10,
      revenue: `-1R per turn`,
      tags: [`Infrastructure`, `Water`, `Pepperville Riverwalk`],
      notes: `This is a 100-year-old pedestrian bridge over the Chattawa River.`,
    },
    {
      name: `Mullet's Tire Yard`,
      value: -10,
      revenue: `70+ = 1R; 0-69 = 0R`,
      tags: [`Automotive`, `Rural`],
      notes: `Because of its junky nature, the tire yard repels people from your city.`,
    },
    {
      name: `Story Unicorn Habitat`,
      value: 35,
      revenue: `150+ = 4R; 0-149 = -4R`,
      tags: [`Mythical`, `Animal`, `Story`],
      notes: `This is a mythical tourist attraction and forest preserve.`,
    },
    {
      name: `The Pepperville Clock Tower`,
      value: 10,
      revenue: `-1R per turn`,
      tags: [`Pepperville`, `Tourist Attraction`, `Pepperville Historic District`],
      notes: `This is an old downtown landmark featured on postcards, WPEP live shots, Christmas lights, and the New Year's countdown.`,
    },
    {
      name: `St. Hilton Country Club`,
      value: 10,
      revenue: `110+ = 2R; 60-109 = 1R; 30-59 = 0R; 0-29 = -1R`,
      tags: [`St. Hilton`],
      notes: `This country club includes a golf course, swimming, and Links Restaurant, and it is owned by Cornelius St. Hilton.`,
    },
    {
      name: `Wakona Village Mini Golf`,
      value: 7,
      revenue: `60+ = 1R; 40-59 = 0R; 0-39 = -1R`,
      tags: [`Wakona`],
      notes: `This is a tire and auto center.`,
    },
    {
      name: `Chattawa County Fairgrounds`,
      value: 15,
      revenue: `100+ = 2R; 60-99 = 1R; 30-59 = 0R; 0-29 = -1R`,
      photoFile: `chattawa-county-fairgrounds.jpg`,
      tags: [`Tourist Attraction`, `Rural`],
      notes: `This fairgrounds hosts many events, including Taste of Pepperville and the Chattawa County Fair. It is centrally located between Pepperville and Ringwald.`,
    },
  ],
};
